from typing import Protocol, List, Optional
from models import User, Recording, RecordingChunk

class UserRepository(Protocol):
    def create_user(self, google_id: str, email: str, display_name: str, avatar_url: str) -> User: ...
    def get_user_by_google_id(self, google_id: str) -> Optional[User]: ...
    def get_user_by_id(self, user_id: str) -> Optional[User]: ...

class RecordingRepository(Protocol):
    def create_recording(self, user_id: str) -> Recording: ...
    def get_recording(self, recording_id: str) -> Optional[Recording]: ...
    def list_recordings(self, user_id: str) -> List[Recording]: ...
    def update_recording_status(self, recording_id: str, status: str) -> None: ...
    def update_recording_transcription(self, recording_id: str, audio_file_path: str, transcription_text: str) -> None: ...

class RecordingChunkRepository(Protocol):
    def add_chunk(self, recording_id: str, chunk_index: int, audio_blob_path: str, duration_seconds: Optional[float]) -> RecordingChunk: ...
    def get_chunks_by_recording(self, recording_id: str) -> List[RecordingChunk]: ...
