from llm.interface import LLMProvider
import requests
import os
from typing import Optional

class RequestYaiProvider(LLMProvider):
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("LLM_API_KEY")
        if not self.api_key:
            raise ValueError("LLM_API_KEY environment variable is required")
        
        self.base_url = "https://api.requestyai.com/v1"  # Example URL
    
    def transcribe_audio(self, audio_path: str) -> str:
        """Transcribe audio file using RequestYAI API"""
        try:
            # Read audio file
            with open(audio_path, "rb") as audio_file:
                files = {"audio": audio_file}
                headers = {
                    "Authorization": f"Bearer {self.api_key}"
                }
                
                # Make API request to RequestYAI
                response = requests.post(
                    f"{self.base_url}/transcribe",
                    files=files,
                    headers=headers,
                    timeout=300  # 5 minutes timeout for long audio files
                )
                
                if response.status_code == 200:
                    result = response.json()
                    return result.get("transcription", "No transcription available")
                else:
                    raise Exception(f"RequestYAI API error: {response.status_code} - {response.text}")
                    
        except Exception as e:
            # Log error in production
            print(f"Transcription error: {str(e)}")
            return f"Transcription failed: {str(e)}"

class MockLLMProvider(LLMProvider):
    """Mock provider for testing purposes"""
    
    def transcribe_audio(self, audio_path: str) -> str:
        """Return mock transcription"""
        return f"Mock transcription for audio file: {audio_path}. This is a sample transcription of the audio content that would be generated by an actual LLM provider."
